### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by wcy1122** [ptx9363/BCNet#4]
Did you use multi-scale for testing to report your performance in IJCAI paper?
And moreover, horizontal flip?
Since I only found {400, 600} scales without horizontal in your code.

Thanks

**Comment by ptx9363** [comment]
The code is exactly what we use in IJCAI paper. 
The multi-scale test setting is that same with _"Weakly- and Semi-Supervised Object Detection with
Expectation-Maximization Algorithm"_. We use {400, 600} due to gpu memory limit.
